WITH temp AS (
    SELECT car.CAR_ID, car.CAR_TYPE, car.DAILY_FEE, discount.DISCOUNT_RATE, history.START_DATE, history.END_DATE, ROUND(car.DAILY_FEE * 30 * (100 - discount.DISCOUNT_RATE) / 100, 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS car
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS history
    ON car.CAR_ID = history.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS discount
    ON car.CAR_TYPE = discount.CAR_TYPE
    
    WHERE discount.DURATION_TYPE = '30일 이상'
)

SELECT DISTINCT CAR_ID, CAR_TYPE, FEE
FROM temp
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM temp
    WHERE (END_DATE>='2022-11-01' AND START_DATE<'2022-12-01') 
) AND FEE >= 500000 AND FEE < 2000000 AND CAR_TYPE IN ('세단', 'SUV')
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC